name: CI

on:
  pull_request:
    branches:
      - master
      - development

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_REGISTRY: https://registry.npmjs.org

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup .npmrc file to publish to npm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ env.NPM_REGISTRY }}
          cache: 'npm'

      - run: npm ci

      - run: npm run ci

      - run: npm run test:unit:ci

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: junit.xml
